:Author: Alexsander Gutierez
:Email:
:Date: 27/12/2023
:Revision: version#
:License: Public Domain

= Project: ESP32 Weather Cloud

ESP32 CAM reading and displaying temperature and humidity data on a 0.96-inch OLED display and sending this data to Arduino Cloud and Google Sheets.

== Step 1: Installation

1. Open this project on your IDLE
2. Instal libs
2. Edit arduino_secrets.h
3. Upload this project in your board
3. Release to the World!

== Step 2: Assemble the circuit

The layout.png file is under development...

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 ESP32_CAM_dec27a                => Arduino sketch folder
  ├── arduino_secrets.h => file for added secrets
  └── ESP32_CAM_dec27a.ino       => main Arduino file
  └── ReadMe.adoc         => this file
  └── sketch.json => this file contains data for Arduino Cloud online sketch editor
  └── thingProperties.h => file containing configuration properties and the use of secrets
....

=== License
This project is released under a MIT License.

=== BOM

|===
| ID | Part name      |  Quantity
| 1 | ESP32-CAM   |  1       
| 2 | Display OLED 0.96p          | 1
| 3| DHT22| 1         
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]

video::preview.mp4[width=640,start=60,opts=autoplay]